import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<header className="mainHeader">
					<nav>
						<ul className="pagesList">
							<li>
								<Link href="/">home</Link>
							</li>
							<li>
								<Link href="/posts">Posts</Link>
							</li>
							<li>
								<Link href="/articles">Articles</Link>
							</li>
						</ul>
					</nav>
				</header>
				{children}
				
			</body>
		</html>
	);
}
